CHAPTERS = [
    {"id": "rest", "numeral": "I", "name": "Charms of Rest", "blurb": "For nights that will not settle and afternoons that fade."},
    {"id": "body", "numeral": "II", "name": "Rites of the Body", "blurb": "For when thinking your way out is not working."},
    {"id": "mind", "numeral": "III", "name": "Incantations of Mind", "blurb": "For pressure, overwhelm, and the stories we tell ourselves."},
    {"id": "hearth", "numeral": "IV", "name": "Hearth Magic", "blurb": "For loneliness, and the people who share your table."},
]

NEEDS = {
    "sleep": "I can't sleep",
    "tired": "I'm running on empty",
    "stress": "I'm stressed",
    "overwhelm": "I'm overwhelmed",
    "low": "My mood is low",
    "lonely": "I feel disconnected",
}

SPELLS = [
    {
        "slug": "sleep-protection", "chapter": "rest",
        "title": "Sleep Protection Ritual",
        "tagline": "A four-step wind-down that teaches the mind that night means safety.",
        "author": "Sara Bahsas",
        "paper": "The Sleep Protection Ritual: Evidence-Based Strategies for Rest and Recovery",
        "needs": ["sleep", "stress"],
        "time": "20 minutes before bed, every night",
        "ingredients": ["Dim lights", "A calming nightly action (tea, reading, music, stretching)", "Paper for tomorrow's worries"],
        "when": ["Racing thoughts at bedtime", "Lying awake while exhausted", "Stress or past experiences keeping you on edge"],
        "caution": "Built from CBT for insomnia (CBT-I). Persistent insomnia, frequent nightmares, or trauma-related sleep problems deserve a proper assessment; CBT-I delivered by a trained clinician is the recommended treatment.",
        "sources": ["sleep-protection-r3", "sleep-protection-r4", "sleep-protection-r5", "sleep-protection-r1"],
        "pages": [
            {"img": "sleep-protection-1", "alt": "Sepia parchment page titled Sleep Protection Ritual with candles, sun, clouds, dreamcatcher and crescent moon illustrations.",
             "transcript": "Sleep Protection Ritual. By Sara Bahsas.\n\nStep I: Dim the World. Begin 20 minutes before bed. Lower bright lights and step away from glowing screens. Darkness helps the brain release melatonin and prepares the body for sleep.\n\nStep II: Quiet the Body. Take slow, steady breaths. Inhale for 4 seconds. Exhale for 6 seconds. Slow breathing calms the nervous system and reduces stress.\n\nStep III: Create a Night Signal. Choose one calming action and repeat it every night. Examples: drink tea, read, listen to calming music, stretch gently. Repeating the same action helps the brain associate this moment with sleep.\n\nStep IV: Clear the Mind. If worries appear, write them down for tomorrow. This allows the mind to release unfinished thoughts before sleep.\n\nOver time, the mind will learn that night means safety and rest."},
            {"img": "sleep-protection-2", "alt": "Matching parchment page titled The Science Behind the Ritual.",
             "transcript": "The Science Behind the Ritual.\n\nWhy the mind refuses the night. When people experience stress or anxiety, the brain can stay in a state of hyperarousal. This means the nervous system remains alert even when the body is tired. As a result, many people experience difficulty falling asleep, racing thoughts, and more.\n\nThe wisdom of sleep science. Psychologists have developed treatments to combat this, such as CBT-I. A systematic review by Isaac et al. examined multiple studies on treatments for insomnia and nightmares in adults experiencing stress or trauma symptoms. Across these studies, sleep-focused therapies led to improved sleep quality, fewer awakenings during the night, reduced nightmare frequency, and decreases in trauma symptoms.\n\nThe Sleep Protection Ritual weaves these strategies into a simple nighttime routine, allowing anyone experiencing stress or restless nights to try it at home and invite rest back into their sleep.",
             "cites": ["sleep-protection-r3"]},
        ],
    },
    {
        "slug": "sleeping-spell", "chapter": "rest",
        "title": "Sleeping Spell",
        "tagline": "Move, unload, then release the body one muscle group at a time.",
        "author": "Nina Ritchie",
        "paper": "Calming Techniques for Improved Sleep Onset and Quality",
        "needs": ["sleep", "stress"],
        "time": "An evening sequence, ending in bed",
        "ingredients": ["Gentle movement", "Pen and paper", "A comfortable bed"],
        "when": ["Too wired or irritable to sleep", "Tension held in the body", "A head full of tomorrow"],
        "caution": "Keep evening movement gentle; vigorous exercise that ends less than an hour before bed can delay sleep. If you have a heart condition or chronic pain, soften the muscle-tensing step.",
        "sources": ["sleeping-spell-r6", "sleeping-spell-r3", "sleeping-spell-r4", "sleeping-spell-r1"],
        "pages": [
            {"img": "sleeping-spell-1", "alt": "Tall parchment page in flowing script titled Sleeping Spell, with a moon, a moth, and a sleeping woman.",
             "transcript": "Sleeping Spell.\n\nThis spell will allow you the ability to sleep deeply in order to receive the best rest and regenerative powers possible. Follow these instructions carefully and you will be granted the deepest and most restful sleep each time you use this spell. This is to be used for anyone too irritable to sleep or suffering from sleep sickness.\n\nThis spell requires your concentration and love. Please accept it with an open mind and heart so that you may receive the most potent benefits. Allow doubtful thoughts to leave your mind.\n\n1. Move your body in a way that feels natural and allows for good blood flow.\n2. Carefully write the worries of your day and stresses plaguing your thoughts.\n3. Lay in your bed in a comfortable position and be aware of your body from toe to head.\n4. Taking each body part in succession, tense the muscles of this area for exactly 10 seconds and then relax it so that not even the smallest muscles remain tensed.\n5. Breathe deeply and allow yourself to fall to sleep.\n\nAllow yourself at least 8 hours of rest before waking for full efficacy. When you wake from this spell your body will feel deeply rested and restored.",
             "cites": ["sleeping-spell-r6", "sleeping-spell-r5", "sleeping-spell-r3", "sleeping-spell-r4", "sleeping-spell-r1"]},
        ],
    },
    {
        "slug": "nap-spell", "chapter": "rest",
        "title": "The Coffee Trap, and the Nap That Saves You",
        "tagline": "When to nap, for how long, and how to fall asleep when you are too stressed to.",
        "author": "Aya Fouad",
        "paper": "Napping in Academic Life: Benefits, Barriers, and Practical Considerations",
        "needs": ["tired", "stress"],
        "time": "20 to 30 minutes, early afternoon",
        "ingredients": ["A quiet spot", "An alarm", "Optional: a 10-minute guided meditation", "Optional: a 5-minute to-do list"],
        "when": ["Afternoon brain fog", "Between classes or study blocks", "After a stretch of poor sleep (longer nap)"],
        "caution": "If you often feel a strong urge to nap alongside low mood, that urge may be a signal to check in with someone, not only a need for rest. Long or late naps can make nighttime sleep harder.",
        "sources": ["nap-spell-r6", "nap-spell-r33", "nap-spell-r28", "nap-spell-r15", "nap-spell-r29", "nap-spell-r30"],
        "pages": [
            {"img": "nap-1", "alt": "Torn kraft-paper collage titled The Coffee Trap and Nap That Saves You, with coffee cups, stopwatches, a kiwi, and a wizard.",
             "transcript": "The Coffee Trap... And Nap That Saves You.\n\nPOV: It's 3 p.m. You're still not done studying, and your final is in 24 hours. Brain fog hits, your eyelids feel like bricks. Do you summon the third coffee... or cast the nap spell?\n\nHow to nap effectively.\nWhen to nap? Aim for the nap sweet spot: 1 to 3 p.m. (after lunch). After that, you might trigger the Grogginess Curse.\nHow long to nap: 20 to 30 minutes, or 90 to 120 minutes, depending on the circumstance.\nWhen to nap 20 to 30 minutes: cast the power nap spell between classes or study sessions. Best if you want to nap regularly (for example, a couple of times a week). Why so short? Less risk of the Grogginess Curse, and it improves alertness, mood, and cognitive functioning.\nWhen to nap 90 to 120 minutes: cast the long nap spell when very fatigued (for example, after a workout) or sleep deprived. Why only then? If you don't follow the rules, you will be cursed with grogginess.\n\nBut... I'm too stressed to nap. We have 3 different napping spells.\n1) Eat kiwifruit. Kiwi contains melatonin (the secret sleep hormone). It can help your brain switch into sleep mode. Eat 1 to 2 kiwis around 1 hour before your nap.\n2) Mini meditation. Meditation tells your brain \"we're safe, we can power down.\" Try 10 minutes of guided meditation (for example, the Calm app) before your nap to fall asleep more easily.\n3) To-do list (a brain dump). Writing a to-do list helps by offloading tasks. 5 minutes before your nap, write the tasks you're holding in your mind. Use paper or a notes app.",
             "cites": ["nap-spell-r21", "nap-spell-r15", "nap-spell-r30", "nap-spell-r8", "nap-spell-r4", "nap-spell-r26", "nap-spell-r13", "nap-spell-r19", "nap-spell-r29"]},
            {"img": "nap-2", "alt": "Second collage page titled Why Nap, with a shield, cartoon brains, and an A-plus grade.",
             "transcript": "Why Nap?\n\n...The question really should be: do you want to ace that exam, or are you okay with being average?\n\nMood Shield! Napping helps reduce negative moods more than just taking a break (Wofford et al., 2022). Napping is linked to feeling happier, having fewer emotional struggles (for example, feeling anxious or depressed), and doing better in school (Liu et al., 2019; Shadab et al., 2026).\n\nMemory Charm! Napping helps memory \"stick\" longer than cramming, especially over a week (Cousins et al., 2019b).\n\nSo, if you want to make sure you ace the cumulative final, I would suggest napping while studying for the midterm. When exhausted, your \"mental sticky note\" (working memory) system is also tired (Ouyang et al., 2025). How do you expect to memorise those notes without being able to remember them short term? Thankfully, naps help restore that ability. Napping also boosts memory for things you read (verbal) and things you see (visual) (Dennison, 2017). Naps help your brain learn and adapt more easily (Tamaki et al., 2020; Shadab et al., 2026).",
             "cites": ["nap-spell-r33", "nap-spell-r35", "nap-spell-r30", "nap-spell-r6", "nap-spell-r28", "nap-spell-r34", "nap-spell-r36"]},
        ],
    },
    {
        "slug": "sense-foraging", "chapter": "body",
        "title": "A Spell for Extinguishing Burnout",
        "tagline": "The Sense Forager's Grimoire: calm the senses when thinking positively is out of reach.",
        "author": "Maya Alves",
        "paper": "Beyond \u201cThinking Positively\u201d: Regulating Emotional Distress Through the Senses",
        "needs": ["stress", "low", "overwhelm"],
        "time": "A few minutes, anytime",
        "ingredients": ["Texture", "Sound", "Aroma", "Warmth or cool", "Something to look at closely", "A taste"],
        "when": ["Heaviness, tension, or exhaustion", "Feeling disconnected from the world around you", "When reasoning with yourself has stopped working"],
        "caution": "What soothes one person can irritate another, so adjust to taste. Use the senses to steady yourself, not to avoid feelings indefinitely. Cold-water practices are not advised for people with heart conditions.",
        "sources": ["sense-foraging-r7", "sense-foraging-r11", "sense-foraging-r10", "sense-foraging-r1", "sense-foraging-r3"],
        "pages": [
            {"img": "sense-foraging-1", "alt": "Aged parchment page with an ornate border titled The Sense Forager's Grimoire: A Spell for Extinguishing Burnout, with a cauldron and two brain engravings.",
             "transcript": "The Sense Forager's Grimoire: A Spell for Extinguishing Burnout.\nCarefully concocted for the witches and wizards who have ever been told to just \"think positively\" when stressed and overwhelmed.\n\nTo be brewed and cast during periods of heaviness, tension, exhaustion, or feeling disconnected from the world around oneself. Beneficial for times when thinking your way out of cognitive turmoil is no longer effective or possible.\n\nThe Default Mode Network: Sorcery from Within. The force that keeps us on autopilot, replaying familiar thoughts, habits, and worries. Beware the grey fog of rumination and burnout, for only by opening yourself to sensation can the world's richness return, helping you notice what your brain usually misses and break free from repetitive mental ruts.\n\nPotion of Sense Foraging.\n1) Choose a few sensory items. The closer, the better.\n2) Focus on your sensations, and block out your woes.\n3) Breathe slowly. Calm the spirits within your soul.\n4) Stay with the experience, even for just a few minutes. Become one with your often-neglected senses."},
            {"img": "sense-foraging-2", "alt": "Parchment ingredients page with a teddy bear, headphones, perfume bottle, mug, landscape, and tongue illustrations.",
             "transcript": "Ingredients. Adjust to psychological taste as needed.\n\nA smidgen of texture. Feel unknown objects with your eyes closed, bringing life back to your fingertips. Feel every seam, stitch, and bump on your clothing. Have you ever stopped to focus on how the fabric drapes?\n\nA sprinkle of sound. Catch subtle noises around you, letting forgotten melodies guide your mind to calmness. Notice the gentle bubbling of your potion, the brushing of your broomstick against the ground, and the crows squawking in the distance.\n\nA hint of aroma. In through the nostrils, and out go your worries. Inhale familiar and new scents, unlocking memories and gentle surprises. Even something as simple as taking a big whiff of room air can reroute your mind.\n\nA dash of temperature magic. Notice warm and cool currents on your skin, letting your senses anchor you to the present. Hold a warm mug, step outside into cool air, or splash cold water on your face. Allow the sensations to soak slowly into your skin and your mind.\n\nA moment of noticing unseen details. Spot five things you missed, then another five, and let your vision spark new ideas. Take in every detail, every colour, and every emotion.\n\nA pinch of flavour. Savour every taste, noticing what you've ignored, and awaken your palate to the present. Try a new dish. Identify the different kinds of flavours. What brings you joy? Chew a few extra times. Feel the flavours roll over your tongue and into your mind.\n\nStir occasionally. Best served warm and in the present moment.",
             "cites": ["sense-foraging-r11", "sense-foraging-r5", "sense-foraging-r4", "sense-foraging-r1", "sense-foraging-r10"]},
            {"img": "sense-foraging-3", "alt": "Parchment caution page with a witch-hat warning sign and a Witch's Brew emblem.",
             "transcript": "A Word of Cauldron Caution.\n\nUnique sensory preferences: what calms one witch may have adverse effects, potentially upsetting a different wizard conducting the same practice.\n\nSkimming the surface of the elixir: these practices can help create moments of calm or grounding, but they do not directly solve the underlying challenges that may be contributing to upsetting emotions.\n\nRisk of emotional avoidance: if sensory activities are used only to escape difficult emotions, they may prevent magical folk from eventually processing those feelings in healthier ways.\n\nA mental wellbeing garnish: sensory practices work best alongside other coping strategies, self-reflection, and, when needed, professional support.\n\nGrounding vs. escaping: sensory self-soothing works best when it is used to reconnect with the present moment, not to avoid difficult emotions. The goal of Sense Foraging is not to eliminate distress, but to create small moments of stability that make it easier to face challenges.\n\nSometimes, calming the mind starts with calming the senses.",
             "cites": ["sense-foraging-r7", "sense-foraging-r9"]},
        ],
    },
    {
        "slug": "steady-motion", "chapter": "body",
        "title": "The Spell of Steady Motion",
        "tagline": "Not the spell of intensity. The spell of steady, kind movement.",
        "author": "Sarah Al-Refae",
        "paper": "Physical Activity as a Scalable Intervention for Mental Well-Being: Evidence for Moderate, Accessible Movement",
        "needs": ["low", "stress", "tired"],
        "time": "About 30 to 45 minutes, 3 to 5 times a week (start smaller if needed)",
        "ingredients": ["Your body", "A small pocket of time", "One kind of movement you dislike the least, or love the most"],
        "when": ["Feeling mentally stuck or lethargic", "Stressed, restless, or tense", "Overwhelmed by the idea of doing wellness correctly"],
        "caution": "More is not always better. If movement becomes punishing or exhausting, scale back. Check with a clinician before starting if you have a health condition that limits activity.",
        "sources": ["steady-motion-r1", "steady-motion-r3", "steady-motion-r2", "steady-motion-r5", "steady-motion-r4"],
        "pages": [
            {"img": "steady-motion-1", "alt": "Navy and gold cover page titled The Spell of Steady Motion with an ornate hamsa and stars.",
             "transcript": "The Spell of Steady Motion. Sarah Al-Refae.\nA wellness spell for lifting mood, calming the mind, and breaking the stillness."},
            {"img": "steady-motion-2", "alt": "Navy page with gold tarot-card outlines describing what the spell does and its ingredients.",
             "transcript": "Feeling better does not need a perfect routine, a gym membership, or endless motivation. This is not the spell of intensity. This is the spell of steady, kind motion.\n\nWhat this spell does. It helps interrupt stillness, ease stress, and gently lift mood. It works best when movement feels doable, steady, and kind.\n\nWhat this spell is for. Use this spell when you feel mentally stuck, lethargic, stressed, restless or tense, or overwhelmed by the idea of \"doing wellness correctly.\" This spell works best when you stop asking \"Can I do the perfect workout?\" and start asking \"What movement can I actually do today?\"\n\nIngredients. You do not need: a gym, expensive gear, athletic skill, a dramatic change, or to become \"that person\" who enjoys exercising. You only need: your body, a small pocket of time, and one type of movement you dislike the least, or love the most.\n\nExamples: walking, light jogging, biking, stretching with music, dancing in your room, playing basketball, following a brief workout video, walking with friends or family, going up and down stairs.",
             "cites": ["steady-motion-r5", "steady-motion-r2", "steady-motion-r1"]},
            {"img": "steady-motion-3", "alt": "Navy page with a gold ornate frame listing five steps.",
             "transcript": "The Spell's Instructions.\n\nStep 1: Pick your motion. Choose one type of movement that feels possible. Not ideal. Possible.\n\nStep 2: Keep it moderate. Aim for movement that wakes you up a little, but does not crush you. You should feel engaged, not punished.\n\nStep 3: Start small. Try around 30 to 45 minutes, or start smaller if required and build up. This is a spell of consistency, not perfection.\n\nStep 4: Repeat through the week. A good target is about 3 to 5 times per week. Enough to generate rhythm. Not so much that it turns into another source of pressure.\n\nStep 5: Track the feeling. Afterwards, ask yourself: Do I feel slightly lighter? Slightly calmer? Slightly clearer? Slightly more like myself? Even a tiny shift counts.",
             "cites": ["steady-motion-r1", "steady-motion-r3", "steady-motion-r2"]},
            {"img": "steady-motion-4", "alt": "Navy page with gold headings: Magical Warning, Ways to Strengthen the Spell, What This Spell Teaches.",
             "transcript": "Magical Warning. More is not always better. If the spell becomes extreme, punishing, overwhelming, or tiring, it may lose its healing quality. This is not a spell about proving discipline. It is a spell about supporting your well-being.\n\nWays to strengthen the spell. Add one of these enchantments.\nCompanion enchantment: get moving with family or a friend.\nMusic enchantment: play music as you move.\nNature enchantment: get outside if you can.\nGentle-start enchantment: tell yourself you only need to start for 10 minutes.\nNo-judgment enchantment: a short walk still counts.\n\nWhat this spell teaches. You do not need to better your mental health through intensity. You do not need a perfect body to feel better. Sometimes well-being starts with something smaller: standing up, stepping forward, and repeating that decision with care to yourself.\n\nAbracadabra.",
             "cites": ["steady-motion-r1", "steady-motion-r3", "steady-motion-r5"]},
        ],
    },
    {
        "slug": "dispel-stress", "chapter": "mind",
        "title": "A Spell to Dispel Stress",
        "tagline": "Create your very own self-affirmation incantation, anchored in what you value.",
        "author": "Brahmleen Kaur",
        "paper": "Exploring self-affirmation practice and its impact on stress management among students",
        "needs": ["stress", "overwhelm"],
        "time": "One quiet moment, practiced often",
        "ingredients": ["1 quiet moment", "1 deep breath", "Mild academic panic (optional)"],
        "when": ["Before exams", "During moments of anxiety", "High-pressure situations, or anytime"],
        "caution": "Self-affirmation can ease the sting of a stressor, but it does not remove structural pressures like workload, finances, or discrimination. Effects in studies are real but modest and depend on context.",
        "sources": ["dispel-stress-r2", "dispel-stress-r3", "dispel-stress-r6", "dispel-stress-r4", "dispel-stress-r1"],
        "pages": [
            {"img": "dispel-stress-1", "alt": "Cream page framed by brown baroque flourishes and roses, titled A Spell to Dispel Stress, with a quill and heart potion.",
             "transcript": "A Spell to Dispel Stress.\nCreate your very own self-affirmation incantation.\n\nStep 1: Find your value. Exempli gratia: resilience is the value you find most important in your life.\n\nStep 2: Create your \"I\" incantation. For resilience: \"I can handle any challenges that come my way.\"\n\nStep 3: Practice, practice, practice. Practice your incantation as you like; say it, write it, sing it, shout it from your window! But you must do it with intention!\n\nArcane mechanism. Channels energy through the mind's reward regions, quieting the body's stress signals and improving performance under pressure.\n\nWhen to cast: before exams; during moments of anxiety; when facing high-pressure situations, or anytime.\n\nIngredients: 1 quiet moment; 1 deep breath; mild academic panic or a crash-out (optional).\n\nThe most reliable magic is not spoken once, but practiced until it becomes belief.",
             "cites": ["dispel-stress-r2", "dispel-stress-r3", "dispel-stress-r7"]},
        ],
    },
    {
        "slug": "metaphor-mirror", "chapter": "mind",
        "title": "The Metaphor Mirror",
        "tagline": "Feeling overwhelmed? Reframe the problem as an image, and find a way through it.",
        "author": "Abbey Kowalski",
        "paper": "Self-Guided Metaphorical Cognitive Restructuring: Developing a Technique to Improve Wellness and Mental Health in Nonclinical Populations",
        "needs": ["overwhelm", "stress"],
        "time": "About 30 minutes, once a week",
        "ingredients": ["Pen and paper", "A comfortable spot", "One problem that is weighing on you"],
        "when": ["A specific worry you keep circling", "Feeling stuck on a problem", "When plain advice is not landing"],
        "caution": "The self-guided version of this technique has not yet been tested in its own study; it is adapted from brief laboratory and classroom trials. If a problem feels too heavy to hold on paper, bring it to someone you trust.",
        "remade": True,
        "sources": ["metaphor-mirror-r4", "metaphor-mirror-r5", "metaphor-mirror-r20", "metaphor-mirror-r19", "metaphor-mirror-r17", "metaphor-mirror-r18", "metaphor-mirror-r16"],
        "pages": [
            {"html": "mm1", "alt": "Remade parchment page introducing The Metaphor Mirror.",
             "transcript": "The Metaphor Mirror. A spell of metaphorical reframing.\n\nWhat it is. Cognitive restructuring spots unhelpful thought patterns and corrects them. The metaphor version does the same work through imagery, turning a problem into something easier to hold, examine, and rethink, with less distress along the way.\n\nWhat it does. In brief trials it reduced distress, catastrophizing, and worry, and improved insight, motivation, and self-efficacy. Metaphors engage imagination and several memory systems at once, so new ways of thinking are more likely to stick.\n\nIngredients: pen and paper; a comfortable spot; one problem weighing on you; about 30 minutes.\n\nWhen to cast: once a week at first, when a specific worry keeps circling.",
             "cites": ["metaphor-mirror-r16", "metaphor-mirror-r4", "metaphor-mirror-r5", "metaphor-mirror-r18", "metaphor-mirror-r17", "metaphor-mirror-r19"]},
            {"html": "mm2", "alt": "Remade parchment page with the three-part ritual and three example solutions.",
             "transcript": "The Ritual.\n\nI. Name the problem. Write a problem you are facing in a sentence or two. Rate your distress from 1 (not at all) to 10 (severe).\n\nII. Look into the mirror. Read this problem and picture it: \"I have no motivation to do anything before I get the result of an important exam.\" Rate each answer for insight and relief (1 to 10):\n(a) \"The test is so important that all you can do is wait for the result.\" A restatement: it repeats the problem.\n(b) \"Live your life on your normal schedule so you won't feel confused.\" A literal answer: some help.\n(c) \"Life is like riding a bike; you must keep moving to keep your balance.\" A metaphor: usually the most relief and insight.\n\nIII. Cast your own. Write a metaphor for your problem. If stuck, write a literal answer first, then recall a time that felt similar and borrow its shape. Rate it again.\n\nAfterwards. Note any new ideas or questions. Plan your next session; the effect grows with practice. If this spell does not suit you, others in this book may.",
             "cites": ["metaphor-mirror-r4", "metaphor-mirror-r20", "metaphor-mirror-r17", "metaphor-mirror-r19"]},
        ],
    },
    {
        "slug": "living-your-values", "chapter": "mind",
        "title": "Living your Values",
        "tagline": "Find your inner compass, notice where you have drifted, and take one small step back.",
        "author": "Noor Chaudhry",
        "paper": "Living your Values",
        "needs": ["low", "stress", "lonely"],
        "time": "One quiet sitting, then one small action the same day",
        "ingredients": ["A moment for yourself", "Something to write on", "Something to write with", "Willingness to take action"],
        "when": ["Feeling directionless, or unsure where you are headed", "Stuck in routines that pull away from what matters", "Leaning on avoidance to get through the day"],
        "caution": "Noor's own caution: this may not help someone in acute crisis — reflecting on values while your behaviour does not match them can add distress or feed rumination. The evidence comes almost entirely from ACT programmes that bundle values work with other components, and mostly from students and largely white samples, so how much the values step alone is doing is still an open question.",
        "sources": ["living-your-values-r8", "living-your-values-r1", "living-your-values-r4", "living-your-values-r3", "living-your-values-r7"],
        "pages": [
            {"img": "living-your-values-1", "alt": "Aged parchment page titled Living your Values in blackletter, with a compass, a candelabra, open books, a quill and inkwell, and a scroll listing what you will need.",
             "transcript": "Living your Values. By Noor Chaudhry.\n\nValues act like a compass to help organize behaviour and provide direction. By reflecting on them, we gain clarity on what matters most, and by putting them into action, we begin to build a life that feels more meaningful.\n\nWhen the road feels long and uncertain, stop for a while, listen to what your inner compass says, and let that guide your next step.\n\nWhat you'll need: A moment for yourself. Something to write on. Something to write with. Willingness to take action.\n\nThe Spell.\n\n1. Find your Inner Compass. Take a deep breath and think about what sort of person you want to be. Ask yourself what values do I want to live by? You can also search up a list of values and choose those that resonate with you the most. If you are still struggling to find your values, ask yourself who do I admire? and what values do they follow?\n\n2. Notice the Gap. Once you choose a value ask yourself: How have my actions recently reflected these values? Write down one behaviour that reflects your value and write one way you feel disconnected from your values. Try not to judge yourself, you are just noticing.\n\n3. Mark the Trail. Based on the value you chose, plan one small action you can take to activate this value. For example, if you value creativity, try making something like a sketch, a fun outfit, a poem or anything you like.\n\nWhen the trail fades and your mind grows foggy, return to your compass. Each small step toward what you care about is a little spell of its own, gently guiding you back toward the life you wish to grow.",
             "cites": ["living-your-values-r8", "living-your-values-r1"]},
        ],
    },
    {
        "slug": "restored-spirits", "chapter": "hearth",
        "title": "The Recipe for Restored Spirits",
        "tagline": "One trusted companion, one simple meal, cooked side by side.",
        "author": "Maria Shaikh",
        "paper": "The Recipe for Restored Spirits: Cooking Together as a Social Pathway to Mental Wellbeing",
        "needs": ["lonely", "low"],
        "time": "30 to 45 minutes, one evening a week",
        "ingredients": ["1 trusted companion", "1 simple recipe", "1 calm kitchen space", "Conversation and laughter"],
        "when": ["Feeling isolated or disconnected", "Low mood and a lack of structure", "Wanting a regular ritual with someone you care about"],
        "caution": "Cooking for others can bring pressure as well as joy. Keep the meal simple; the purpose is connection, not perfection.",
        "sources": ["restored-spirits-r3", "restored-spirits-r6", "restored-spirits-r5", "restored-spirits-r7", "restored-spirits-r4", "restored-spirits-r2"],
        "pages": [
            {"img": "restored-spirits-1", "alt": "Pale parchment page in blackletter titled The Recipe for Restored Spirits, with a steaming cauldron, candles, and botanical watermarks.",
             "transcript": "The Recipe for Restored Spirits.\n\nGather the following: 1 trusted companion; 1 simple recipe; 30 to 45 minutes of shared time; 1 calm kitchen space; a pinch of curiosity; a measure of patience; a generous serving of conversation; a handful of laughter.\nOptional additions: soft music; candlelight; a warm drink to share.\n\nThe Recipe.\nStep I: Choose the day. Select one evening each week when both companions are free.\nStep II: Select the meal. Choose a dish that is meaningful yet simple. The purpose is connection, not perfection.\nStep III: Prepare together. Enter the kitchen and divide the tasks. Chop, stir, season, and cook side by side.\nStep IV: Speak and listen. While cooking, share stories of the week, thoughts, or quiet moments.\nStep V: Share the meal. Sit together and enjoy the food you created.\nStep VI: Reflect. After the meal, take a moment to reflect on how the experience felt.\n\nRepeat weekly for stronger magic.",
             "cites": ["restored-spirits-r5", "restored-spirits-r7", "restored-spirits-r2", "restored-spirits-r4"]},
            {"img": "restored-spirits-2", "alt": "Matching page with Notes from Scholars, Magic of the Practice, and Sources of Knowledge, illustrated with books and a glowing tome.",
             "transcript": "The Recipe for Restored Spirits.\n\nNotes from Scholars. Scholars of later years have taken an interest in the old wisdom of shared meals and cooking rituals. Preparing food together can improve mood, self-esteem, social connection, and overall well-being (Farmer et al., 2018). Those who share meals more often report fewer depressive and anxiety symptoms and stronger emotional well-being (Utter et al., 2017). Lend support to what many households have long believed: that gathering to cook and eat together may restore the spirit as well as nourish the body.\n\nMagic of the Practice. Cooking uses thinking, planning, sensing, and movement (Dean et al., 2021). Activates brain pathways linked to mood and emotional balance (Lambert, 2006). Reduced stress, anxiety, and depressive feelings (Hill et al., 2007). Those who dine with close companions often eat more than when they eat alone (Hamburg et al., 2014).\n\nSources of Knowledge: Dean et al. (2021); Farmer et al. (2018); Hamburg et al. (2014); Hill et al. (2007); Lambert (2006); Utter et al. (2017).",
             "cites": ["restored-spirits-r3", "restored-spirits-x5", "restored-spirits-x1", "restored-spirits-x4", "restored-spirits-x3", "restored-spirits-x2"]},
        ],
    },
]
